AccordionItem closes when another is opened, add free boolean for opening multiple
bootstrap-vue/bootstrap-vue-next pull request #1000
Opened 2023-04-04 11:32 UTC by xvaara

As the title says.
fixes #994 
Adds v-modal to BAccordion that is the id of the open accordion. 
Add free booleanish to open multiple
Integrate more with BCollapse

2023-04-04 13:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +export interface BCollapseProps {
I don't think you're allowed to export from script setup

2023-04-04 13:17 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +export interface BCollapseProps {
I think because it's only typescript functionality it's allowed. It is exported before the vue compiler munches over the setup part. Not sure, but some random stackoverflow post said you could do this and it works... so 😅🤷 up to you.

2023-04-04 13:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +export interface BCollapseProps {
Okay, so this is possible. I thought it would first error on you because there is an eslint rule to disable named exports in script setup.

However this is a type and will not suffer from the limitation presented by (exporting a variable from a setup function that is inside of a export default object), just doesn't make sense.

However, there is still an issue with the usage of this, I will describe in a different comment

2023-04-04 13:42 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +export interface BCollapseProps {
it's used in vue docs on script setup: https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration

2023-04-04 13:43 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +interface BAccordionItemProps extends BCollapseProps {
This is **impossible** syntax. Extending prop types will break Vue as it's currently not supported by the Vue compiler. Your best bet is to just duplicate the props and leave a note. Alternatively, you could revert the component to <script> and use real objects, as shown in BLink & components that depend on its props. However, this is not the best option, I'd prefer to just duplicate the props and use a note.

2023-04-04 13:46 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +export interface BCollapseProps {
> it's used in vue docs on script setup: https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration

The problem is not with exporting a type, the problem is with extending a prop type, as the Vue compiler cannot crawl types:
https://vuejs.org/guide/typescript/composition-api.html#syntax-limitations 
> This is because Vue components are compiled in isolation and the compiler currently does not crawl imported files in order to analyze the source type. This limitation could be removed in a future release.

2023-04-04 13:54 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +interface BAccordionItemProps extends BCollapseProps {
it works, You can't export an extended interface, that's what vue compiler doesn't support.
here's the bug for that: https://github.com/vuejs/core/issues/7794

2023-04-04 14:06 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +interface BAccordionItemProps extends BCollapseProps {
ah now I get what you mean:
https://sfc.vuejs.org/#eNqVkd1ugzAMhV/Fyk1biZ97RpH28wB7gNwwaihVcSLbtJ0Q774AnVZ106bdRIljfzrneDCP3ienHk1mcqm49QqC2ns4ltRsrVGxprDUdt6xgr57hAFe2Xl5KgVhhJpdB6skfXbdDFqFZlLkuqxwaQS8KNJObsYGqJ3LQJRbagIELFWORMHPA1s4t7p/wbrsjyrrHdYt4Tydz2ex3kQwjJsHS3m6qC5MZBaRcVf65CCOgqXBUmBfP4KTDObKVAtSp7c1e1UvWZpKXU36D5I4btJwS7gnbTtMULr4jd1ZkAPYmuiGkYbiCTnm4BAZ+TfmXes37oQdLY3Bymeaf6wFL/Na7gK/Rjwt6yvj/yU8IX5MefwAg0rGqA==

2023-04-04 14:10 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +interface BAccordionItemProps extends BCollapseProps {
we don't need them (BCollapseProps) in vue side anyway. But it works on the editor, I get the code completion from BCollapseProps for BAccordionItem. Every prop that BAccordionItem uses is defined in that interface. Everything else is forwarded to BCollapse.

2023-04-04 14:45 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +interface BAccordionItemProps extends BCollapseProps {
So if vue implements a fix for the extends interface, It'll break this. So maybe better to do this the hard way. 😅

2023-04-04 15:13 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
> +const emit = defineEmits<(e: 'update:modelValue', value: string) => void>()
```suggestion
const emit = defineEmits<(e: 'update:modelValue', value: string) => void>()

```

2023-04-04 15:13 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> -watchEffect(() => {
Why did you remove this watchEffect

2023-04-04 17:53 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> -watchEffect(() => {
it was launching open() twice, don't know why. As general I've had so much problems with watchEffect in this project that it's the first thing I remove and usually it works.

2023-04-07 19:12 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> -watchEffect(() => {
> it was launching open() or close() everytime mounted, don't know why. As general I've had so much problems with watchEffect in this project that it's the first thing I remove and usually it works.

You should try to take a look at https://vuejs.org/api/reactivity-core.html#watcheffect and their 
```ts
interface WatchEffectOptions {
  flush?: 'pre' | 'post' | 'sync' // default: 'pre'
  onTrack?: (event: DebuggerEvent) => void
  onTrigger?: (event: DebuggerEvent) => void
}
```
I'd try messing around with the flush value. It's kind of a longshot, but who knows, maybe it will magically fix the issue?

2023-04-09 20:43 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +watch(visibleBoolean, () => {
You will likely want 
```ts
watch(visibleBoolean, (newValue) => {
  newValue ? ...
}
```

2023-04-11 20:33 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> -watchEffect(() => {
It doesn't. watchEffect is run always, not only on change. It also watches all the reactive variables in the functions.

2023-04-11 23:16 UTC, VividLemon requested changes

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
> +  openItem: modelValue,
I'd suggest wrapping this in readonly

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +<script lang="ts">
Move this block to the bottom of the file

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +
```suggestion
```

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const emit = defineEmits<BAccordionItemEmits>()
```suggestion
const emit = defineEmits<BAccordionItemEmits>()

```

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    openItem.value = computedId.value
I am not certain, but I'm wondering if you can assign this in the provide default
```ts
const {openItem, free} = inject(accordionInjectionKey, {
  openItem: ref(computedId.value),
  free: ref(false),
})
```
There was that issue with some values not being in the correct state in between the finishing of mounting, and the finishing of the execution of the onMounted callback. I assume this would suffer from the same issue.

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +  modelValue: false,
Ensure you have fetched the main branch. There may be eslint rules that may be missing. (vue/require-default-prop)

2023-04-11 23:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/keys.ts
> +  openItem: Ref<string>
Wrap these in Readonly<> & use the equivalent runtime vue readonly() if needed

2023-04-12 01:24 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    openItem.value = computedId.value
The parent doesn't know what might be open, if accordionItem is opened with visible or toggle Booleanish. If multiple is open the "last one wins".

2023-04-12 03:00 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
> +  openItem: modelValue,
You created a method to set this, but didn't wrap it in readonly

2023-04-12 13:12 UTC, merged