Navbar dropdown and collapse fix
bootstrap-vue/bootstrap-vue-next pull request #1001
Opened 2023-04-04 13:15 UTC by xvaara

Add inject/provide to collapse
in dropdown-item and b-link close the collapse if collapse isNav is true

fixes #721

2023-04-07 19:01 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +<script lang="ts">
```suggestion

<script lang="ts">
```

2023-04-07 19:08 UTC, VividLemon requested changes

2023-04-07 19:08 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
> +const {close: _closeCollapse, isNav: inNavCollapse} = inject(collapseInjectionKey, {
I think this might break reactivity... I'm not sure though. (The same as doing `const {foo} = props`)

It would be nice instead if this followed the structure of `inject(key, null)` with explicit null checks. Not that the default values wont work, It just makes it easier to differentiate between when there is no parentData, and when there is.

2023-04-07 19:08 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
> +    // do nothing
If you did the above suggestion, you wouldn't need to do this

2023-04-07 19:08 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BLink/BLink.vue
> +    const {close: _closeCollapse, isNav: inNavCollapse} = inject(collapseInjectionKey, {
Is there really a need to couple these two components together?

2023-04-07 19:08 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BLink/BLink.vue
> +      @click="($event: Event) => {
This kind of looks ugly, Should probably just make a function for this

2023-04-07 19:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
> +    // do nothing
The: 
  close: () => {
    // do nothing

2023-04-11 17:54 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BLink/BLink.vue
> +    const {close: _closeCollapse, isNav: inNavCollapse} = inject(collapseInjectionKey, {
It's required to collapse navbar dropdown on narrow screens on navigation.

2023-04-11 19:37 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BLink/BLink.vue
> +      @click="($event: Event) => {
the other function is from the v-slot, so we'd need to pass that and event around... it's almost as messy.
```
@click="doTheThing(navigate, $event)"

and 
doTheThing = (fn, e) => { 
   fn?.(e)
   closeCollapse?.()
}
```
Is that any cleaner?

2023-04-11 23:02 UTC, VividLemon requested changes
Only some minor fixes on this one.

2023-04-11 23:02 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +
```suggestion
```

2023-04-11 23:02 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +  id: computedId,
Ensure that any of these are readonly refs. (useBooleanish returns a readonly ref, so you don't need to do those. But I'm worried about the 'visible' property.)

2023-04-11 23:16 UTC, VividLemon commented
Also ensure you've fetched the main branch as it is possible to be missing vue/require-default-prop. Treat those issues as errors.

2023-04-12 02:00 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue
> +  center?: Booleanish
I think they are all on the new props now.

2023-04-12 02:38 UTC, merged