enable fade on tabs, redo tabs only when slot is changed.
bootstrap-vue/bootstrap-vue-next pull request #1035
Opened 2023-04-12 20:20 UTC by xvaara

fixes #251 

split the tabs to two, watch for changes in slots.default and recreate the tabs only then. Otherwise we're creating the tabs object on each change and the ID:s change.
Then have computed for the local changes.

2023-04-12 22:27 UTC, VividLemon requested changes

2023-04-12 22:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
> +  setTimeout(() => {
I saw this same 'setTimeout' hack in a previous PR.

What is the purpose of this?

If it's to force nextTick, perhaps you should use `{ flush: 'post' }` instead

2023-04-13 08:45 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
> +  setTimeout(() => {
The show class needs to be in the dom before we add the active class for the animation to launch. It's just to delay the show. `nextTick` / `{ flush: 'post' }` for some resaon didn't work, the dom isn't updated in time. Probably they have some optimizations.

2023-04-13 15:16 UTC, merged

2023-04-13 17:57 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
> +  setTimeout(() => {
Probably. It would require some bigger changes, and this was a quick fix. If there are any problems with this we can revisit this.