fix(BModal): multiple open modals and performance issues
bootstrap-vue/bootstrap-vue-next pull request #1073
Opened 2023-04-29 22:41 UTC by aki77

# Describe the PR

fix #1070 and #1030

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-04-29 22:51 UTC, VividLemon requested changes

2023-04-29 22:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +const useSharedModalManager = createSharedComposable(() => {
Extract all this logic out into a separate composable. 

I say create a single file. `useSharedModalManager`. Then put all the relevant logic from there into it.

2023-04-29 22:53 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    if (document) {
I'm not sure if this watch would be ssr friendly. Specifically: 

1. You start a modal open
2. Ssr renders without document -- does not add classList to body
3. Sends over to client,
4. Hydration mismatch.

2023-04-29 22:55 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +  const modalOpen = ref(false)
It doesn't appear that this value ever actually will change. I'm not sure the intended effect here

2023-04-29 23:06 UTC, aki77 commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +const useSharedModalManager = createSharedComposable(() => {
I understand.
Do I just separate them in the `bootstrap-vue-next/src/composables` directory?

2023-04-29 23:08 UTC, aki77 commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    if (document) {
I think the original implementation also caused hydration mismatch, am I mistaken?

2023-04-29 23:11 UTC, aki77 commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +  const modalOpen = ref(false)
I tried to change the original implementation as little as possible.

https://github.com/bootstrap-vue/bootstrap-vue-next/blob/e2860b7080721aa811a557640115dd6484e180e0/packages/bootstrap-vue-next/src/components/BModal.vue#L418

2023-04-29 23:47 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +const useSharedModalManager = createSharedComposable(() => {
Keep them together. One can be a private function since it is only used in one place

2023-04-29 23:47 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    if (document) {
It should not have. Vueuse handles ssr afaik

2023-04-29 23:59 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +  const modalOpen = ref(false)
The actual return value of modalOpen didn't have any affect. It simply placed the class value on the body

2023-04-30 01:16 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useModalManager.ts
> +export default function useModalManager(modalOpen: Ref<boolean>): void {
```suggestion
export default (modalOpen: Ref<boolean>): void => {
```

2023-04-30 01:37 UTC, merged

2023-04-30 01:39 UTC, aki77 commented
Thanks!

2023-04-30 05:10 UTC, VividLemon commented
I'm surprised I didn't think of this solution during my first implementation. Simple, yet creative