Offcanvas Bootstrap JS dependencies removed
bootstrap-vue/bootstrap-vue-next pull request #858
Opened 2022-12-30 00:42 UTC by aceofwings

# Describe the PR

Remove Bootstrap Dependencies from  Offcanvas

## Small replication

If the change is large enough, a small replication can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [] Bugfix :bug: - `fix(...)`
- [X] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2022-12-30 01:13 UTC, VividLemon requested changes

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +import BTransition from '../BTransition/BTransition.vue'
BTransition is never used in the component (but should be)

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const offcanvas = wrapper.find('.offcanvas')
read other comment about `.find`

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const $transition = $overlay.getComponent(BTransition)
This is under the impression that the component is using BTransition. Tbh I'm surprised this doesn't error

Second, this line of code is under the predicate that `BTransition` exists. 

In general, you should first check that each component exists with explicit checks
```ts
const $overlay = wrapper.findComponent(BOverlay)
expect($overlay.exists()).toBe(true)
```
In next test
```ts
const $overlay = wrapper.getComponent(BOverlay)
const $transition = $overlay.findComponent(BTransition)
```
It creates a lot of tests, but it makes them more descriptive. 

findComponent should only be used when testing the existence of an element or component, getComponent should always be used after the test for existence. (findAll variants break this as they work slightly differently)

https://test-utils.vuejs.org/guide/essentials/conditional-rendering.html#using-find-and-exists

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const offcanvas = wrapper.find('.offcanvas')
read other comment about .find, (this happens a few times)

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const $offcanvas = wrapper.find('.offcanvas')
I tend to avoid the testing for the existence of the _class_. You should instead refactor this to check for the _element_, and ensure the _element_ has the _class_. Class existence can cause brittle tests, and I think it's only used once in all other tests.

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +  // skip('has data-bs-scroll', async () => {
Just delete this block. It will never return

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const [$header] = offcanvas.findAll('div')
Why use findAll if you're only checking for the first element?

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/index.ts
> +export {default as BOffcanvas} from './BOffcanvas/BOffcanvas.vue'
Passive gloat, but this refactoring of components/index.ts and the main export file caused a massive 50% decrease in unpacked package size :)

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/styles/styles.scss
> +@import "../components/BOffcanvas/offcanvas";
Review other comment, but I truly believe there is a way to use bootstrap classes for this instead and we don't need to make custom classes.

2022-12-30 01:13 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +  const mountComponent = () => {
I recall there used to be documentation that referred to doing this, essentially creating a "componentFactory". Instead, I'd recommend trying
```ts
const componentFactory = () => mount(BOffcanvas ...)
```

2022-12-30 01:14 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +  <b-overlay variant="dark" :show="showBackDrop" fixed="true" no-wrap />
Not relevant to your pr

2022-12-30 01:14 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +  emit('show')
Isn't a required change, but if you do not decide to change it, please leave a TODO note for me

2022-12-30 01:16 UTC, aceofwings commented
making several updates will respond when I resolve some stuff.

2022-12-30 01:42 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +  <transition name="slide" :on-after-enter="OnAfterEnter">
yep will do that

2022-12-30 01:46 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/_offcanvas.scss
> +.slide-enter-active,
well sadly the classes work but the initial animation will not start and trigger proper event handling, thus there is a lag on button click using standard event handling of the animations. I tried to keep things to how Btoast handles animation but due to the initial transform state it does not work.

`
      &.offcanvas-bottom {
        right: 0;
        left: 0;
        height: var(--#{$prefix}offcanvas-height);
        max-height: 100%;
        border-top: var(--#{$prefix}offcanvas-border-width) solid var(--#{$prefix}offcanvas-border-color);
        transform: translateY(100%); // cannot work with b-transition
      }`

2022-12-30 01:47 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +  <b-overlay variant="dark" :show="showBackDrop" fixed="true" no-wrap />
oh no

2022-12-30 02:30 UTC, aceofwings commented on packages/bootstrap-vue-3/src/styles/styles.scss
> +@import "../components/BOffcanvas/offcanvas";
I don't think it can be done unless the initial transform can be applied at the start of the animation. Of course you can hook into the animations and use the on enter to create a JavaScript( I have not tried ), but this is far easier. Trust me I went looking at using the original classes, but the animation did not correctly start.

2022-12-30 02:32 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const offcanvas = wrapper.find('.offcanvas')
might have to find another day to refactor test cases that are from previous contributions.

2022-12-30 03:18 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +const OnBeforeLeave = () => {
The changes you made here aren't quite what I meant
```ts
const onAfterEnter = () => emit('shown')

const onAfterLeave = () => emit('hidden')
```
You don't need to make the isHiding/isTransitioning refs.

2022-12-30 03:21 UTC, VividLemon commented on apps/docs/docs/components/Offcanvas.md
> +<ClientOnly>
The issue before with rendering with SSR was that the components that used Bootstrapjs would throw errors. Since you have removed the bootstrap js in this component, you can remove `<ClientOnly>` when rendering these components (assuming other used components are also SSR friendly)

2023-01-04 18:40 UTC, aceofwings commented on apps/docs/docs/components/Offcanvas.md
> +<ClientOnly>
until the library is SSR friendly these will have to remain even though the components themselves are SSR ready.

2023-01-04 18:41 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +const OnBeforeLeave = () => {
I think the only reason I do this is to preserve bootstraps's hiding and showing class additions.

2023-01-04 18:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +])
```suggestion
const computedClasses = computed(() => [
  `offcanvas-${props.placement}`,
  {
    show: props.modelValue && !isShowing.value,
    hiding: isHiding.value,
    showing: isShowing.value,
  },
])
```

2023-01-04 18:46 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +const OnBeforeLeave = () => {
As far as I can see, you're not using those values in the file

2023-01-04 18:47 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +
```suggestion

```

2023-01-04 18:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BOffcanvas/BOffcanvas.vue
> +])
`show: modelValueBoolean.value`

2023-01-04 19:18 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/BOffcanvas/offcanvas.spec.ts
> +    const [$header] = offcanvas.findAll('div')
just adjusting existing test cases. These tests were introduced a year ago. I have started making way on writing them to make more sense

2023-01-04 19:18 UTC, aceofwings commented on packages/bootstrap-vue-3/src/components/index.ts
> +export {default as BOffcanvas} from './BOffcanvas/BOffcanvas.vue'
very passive

2023-01-04 19:39 UTC, aceofwings commented
Let me know what you think. I did not make the b-transition change just because I had to do a custom transition and I the transition classes applied by b-transition cannot be overridden in its currently implementation.

2023-01-07 01:01 UTC, VividLemon commented
I'll give a re-review this weekend. 

> Let me know what you think. I did not make the b-transition change just because I had to do a custom transition and I the transition classes applied by b-transition cannot be overridden in its currently implementation.

2023-01-14 18:47 UTC, VividLemon commented
I took the liberty of pulling in your work and merging the upstream branch. (There are a few merge conflicts). I have spruced up the updated BOffcanvas to include some extra features. Such as, lazy loading, preventable closing, teleport to body, and some others. The last thing I am working on is getting the transition states to be 100% bootstrap css (and our js). I have added you as a co-author on that commit to give credit for your work, and will resubmit a new PR soon. Closing this one in the meantime

2023-01-14 18:47 UTC, closed without merging