remove popperjs and convert to floating-ui
bootstrap-vue/bootstrap-vue-next pull request #938
Opened 2023-02-20 15:17 UTC by xvaara

Many breaking changes!

Need to see if the logic with the component is valid in your opinion.
```html
 <b-popover>
  <template #title>
    Title
  </template>
  <template #content>
    Content
  </template>
  <b-button>Trigger</b-button>
</b-popover>
```

the first element in default slot is the trigger.
Added some features, will document later.

2023-02-23 01:48 UTC, VividLemon requested changes
Some changes, some thoughts.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +})
```suggestion
onMounted(bind)
```

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
>  })
```suggestion
onBeforeUnmount(unbind)
```

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/popover.spec.ts
> +    const [$div] = wrapper.findAll('div.popover')
There's no point to using findAll if you're simply going to use the first item. You want to check the existence of the component first, then do your check
```ts
it('has div.poper', () => {
const $div = wrapper.findd('div.popover')
expect($div.exist()).toBe(true)
})
// Then 
it('has static class popover', () => {
const $div = wrapper.get('div.popover')
// rest of code
})
```
It's more writing, but more explicit and makes failing tests, logically make more sense

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/floatingUi.ts
> +export function resolveBootstrapPlacement(placement: Placement): string {
Prefer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/floatingUi.ts
> +export function resolveFloatingPlacement({
Prefer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/sanitizer.ts
> +export function sanitizeHtml(
Prefer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +    el.addEventListener('pointerenter', addTooltipElement)
I'm not exactly sure how well composables will work in this context. But you could use the `useEventListener` from Vueuse. As well as possibly using the useFocus. There's also one for hovering, which I used somewhere else, but I don't remember the name of it. -- I'm not sure how well this would work though.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +  const tooltip = document.createElement('div')
Afaik, you may be able to use h() instead of all this manual dom manipulation. (I think you could, but I'm not 100%)

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/popover.spec.ts
> +    const [$div] = wrapper.findAll('div.popover')
The same issue mentioned before with the findAll usage should be applied universally.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  <span ref="placeholder" />
You may want to consider where to set $attrs, since the multiple root nodes will not know where to place them.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const elementRef = ref<HTMLElement>()
No other component appends "Ref" to a template ref. It may be a good idea to bring this in line with other components.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const elementRef = ref<HTMLElement>()
```suggestion
const elementRef = ref<HTMLElement | null>(null)
```
This should apply to the rest.
Undefined and null work the same in these situations, but null is more explicit

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  } else if (target instanceof HTMLElement) {
Why nest in an `else if` if you're going to return? I prefer the style of 
```ts
if(this){
 return 'a'
}
if(otherThis){
 return 'b'
}
// etc
```
It's style, but I subjectively feel that the styles should be similar and uniform throughout components. That way it's easier for future contributors to understand and be comfortable with a uniform style. Such non-uniformity is one of the issues I have with reviewing Bootstrap-vue code.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> -import {Popover} from 'bootstrap'
:partying_face:

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  triggers?: string
This should probably be strongly typed. That way it's a bit more straightforward to the user

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  (e: 'show'): void
Review: https://bootstrap-vue.org/docs/components/popover#comp-ref-b-popover-events

Please match up the events in BV to be ported over to BVN. Hide/show are cancellable in this context. There's an example in BModal on how to set up cancellable events. (I have yet to figure out how to make the "show" cancel correctly -- it's transition to cancel starts before preventDefault is possible to be called. But that's a later issue)

It's something that will need to be done eventually regardless.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const arrowStyle = ref({position: 'absolute'} as CSSProperties)
Why not `const arrowStyle = ref<CSSProperties>({...})`?

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +function toggle() {
Preffer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +function show() {
Prefer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +function dohide() {
Prefer arrow functions

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
It would be nice if Tooltip was also a composable. Afaik, it is possible to do something with the h() fn in composables.

What I would imagine this to be like, is, extract some of the Tooltip stuff written here out into an actual .vue file. Then, (assuming you can use h() in directives), use h() here, render the .vue file. Then, in the composable you can also do the same. 

The composable `useTooltip` would essentially take in a target "template ref", (or selector if you want to be cool like that). Then the second param would be an options object. Which would have the same purpose as some of the other details here, things like delay, variant, etc.

Most of the code you have written here is still usable, just needs to be converted to a .vue file.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
Bootstrap-vue does something similar, to where the BTooltip is an actual .vue file. How they get it to render is a bit over me. But the point is, we should make the .vue file, and figure out how to use it in a directive after... Or if you're feeling adventurous, you could make a fake mock up first, demonstrating the usage.

2023-02-23 01:48 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
The same general idea in this thread should be extended to BPopover as well. They should both be true components, both with a Directive & Composable

2023-02-23 20:30 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +    el.addEventListener('pointerenter', addTooltipElement)
We can't use composables in directives as I understand it. Tried it, didn't work, googled it found out they don't work. Would have liked to use them for sure.

2023-02-23 20:37 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +  const tooltip = document.createElement('div')
didn't think about that, haven't seen that in any non render function context. Will check it out.

2023-02-23 20:43 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
It seemed more complicated that doing these few dom manipulations. You need to build a new vue instansce and mount it to dom: https://github.com/Akryum/floating-vue/blob/main/packages/floating-vue/src/directives/v-tooltip.ts#L57

want me to give it a go?

2023-02-23 20:44 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +    el.addEventListener('pointerenter', addTooltipElement)
to use composables we'd need to rebuild these as components.

2023-02-23 20:46 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
Yes. This is preferable since if we use real .vue components, we can spread them to directives and composables. Its a shame the approach us a bit convoluted, but you could likely make a util called "mount component" or something to abstract the business logic out

2023-02-23 20:49 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  } else if (target instanceof HTMLElement) {
It was a else if to start with... will change them.

2023-02-23 20:51 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const arrowStyle = ref({position: 'absolute'} as CSSProperties)
There was some weirdness with this.  I think I just tested many things and left it like that 😄, will change.

2023-02-23 20:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  } else if (target instanceof HTMLElement) {
I may have not seen the diff. Its whatever, it happens

2023-02-23 20:52 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/popover.spec.ts
> +    const [$div] = wrapper.findAll('div.popover')
I just did something that works and did a search&replace for them. 😅

2023-02-23 21:02 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
I was also thinking... Do we need to support html in tooltip directives? bootstrap does. We could get rid of sanitizer if not. I'd like not to open us for XSS vulnerability. 😁

2023-02-23 21:05 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
I feel like we should.

2023-02-23 22:36 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  triggers?: string
sounds like a good idea. Makes it kore standard to other components

2023-02-23 23:25 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +  alignCenter?: Booleanish
You want me to remove them from this pr?

2023-02-23 23:29 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +  alignCenter?: Booleanish
Yes

2023-02-23 23:33 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +  triggers?: string
I did this already. I added "manual" so that people can build their own interaction in the default slot.

2023-02-24 04:35 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BTooltip.ts
> +import {type Directive, type DirectiveBinding, toRef} from 'vue'
Checkout the component versions 😁

tooltip is just popover with different class, so I just created that option to popover and created a proxy component for tooltip.

2023-02-24 04:37 UTC, xvaara commented on packages/bootstrap-vue-next/src/utils/floatingUi.ts
> +  el.$__app = createApp({render: () => h(BPopover, {...el.$__state?.value})})
I was really surprised that this worked 😂

2023-02-26 17:09 UTC, VividLemon requested changes

2023-02-26 17:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +// const showState = useVModel(props, 'modelValue', emit, {passive: true})
Why not use this?

2023-02-26 17:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +// const id = useId('b-popover', props.id)
Dead and duplicated on line 169

2023-02-26 17:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const placeholder = ref<HTMLElement | null>()
```suggestion
const element = ref<HTMLElement | null>(null)
const target = ref<HTMLElement | null>(null)
const arrow = ref<HTMLElement | null>(null)
const trigger = ref<HTMLElement | null>(null)
const placeholder = ref<HTMLElement | null>(null)
```

2023-02-26 17:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const ishtml = computed(() => props.html === 'thisIsDangerous')
This doesn't look right.

2023-02-26 17:09 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +    [type]: true,
When you have values like this that are always rendered, you can do something more like this: 
```ts
const computedClasses = computed(() => [
    type, // These can be in the array because they're always rendered, ie `[type]: true`
    `b-${type}`,
    {  // These go into an object because they are only soometimes rendered
        [`b-${type}-${props.variant}`]: props.variant !== undefined
       // etc
    }
]
```
BOffcanvas has a quick and simple example

2023-02-26 17:10 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/popover.spec.ts
> +  it('has div.poper', () => {
```suggestion
  it('has div.popover', () => {
```

2023-02-26 20:32 UTC, VividLemon commented
Sorry about the merge conflicts. I refactored the usage of ts `Array<>` syntax to be `[]` syntax

2023-02-27 14:00 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const ishtml = computed(() => props.html === 'thisIsDangerous')
Yeah, I relly don't want users to create xss bugs with this. Maybe I just force sanitize all the input if :html="true" ?

2023-02-27 14:01 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +// const showState = useVModel(props, 'modelValue', emit, {passive: true})
the useVModel doesn't work with delay, we'd need another ref that works with that. So I just created one with the ref + watch that does both.

2023-02-28 15:08 UTC, merged