Collapse native vue, no more bs.js!
bootstrap-vue/bootstrap-vue-next pull request #969
Opened 2023-03-12 19:33 UTC by xvaara

No more bootstrap.js!

SSR works! The docs can be build without <ClientOnly>! I belive nuxt works also!

tried to keep the changes to minimal on places.

changed the v-b-toggle to work with events, and now toggle, offcanvas and modal listen to "toggle" event.

As a test I remove bootstrap in playground and only added it's css in link tag in the index.html file.

In bootstrap-vue-next we only need few scss functions/variables/mixins from bootstrap npm package.

2023-03-13 14:27 UTC, VividLemon requested changes

2023-03-13 14:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +useEventListener(element, 'toggle', () => {
BModal has it's own vBModal directive. It would be nice if that worked

2023-03-13 14:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
>  })
```suggestion
watchEffect(() => {
  visibleBoolean.value ? open() : close()
})
```

2023-03-13 14:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +})
```suggestion
watchEffect(() => (open.value = visibleBoolean.value))
```

2023-03-13 14:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +if (visibleBoolean.value) {
This is probably code that runs onMounted

2023-03-13 14:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +if (visibleBoolean.value) {
But it's possible it would be done automatically from the watchEffect

2023-03-14 22:34 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +useEventListener(element, 'toggle', () => {
Commited

2023-03-14 22:43 UTC, VividLemon commented on apps/nuxt-playground/.npmrc
> +shamefully-hoist=true
This will not work
https://github.com/pnpm/pnpm/issues/5627#issuecomment-1312851603

2023-03-14 22:45 UTC, VividLemon commented on apps/nuxt-playground/.npmrc
> +shamefully-hoist=true
I would be fine with moving this npmrc to the root of the project. Hopefully it would be a temporary solution until Nuxt gets their act together.

2023-03-14 22:51 UTC, xvaara commented on apps/nuxt-playground/.npmrc
> +shamefully-hoist=true
nuxt did that by default when I just ran `npx nuxi@latest init nuxt-playground`. Shall I move it?

2023-03-14 22:53 UTC, VividLemon requested changes

2023-03-14 22:53 UTC, VividLemon commented on apps/nuxt-playground/components
> +../playground/src/components
I don't know what this is

2023-03-14 22:53 UTC, VividLemon commented on apps/playground/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" cr
I've seen you do this a few times... It may be better to declare Bootstrap as a dependency, so it can be easily identifiable in the project -- ie so it can be updated in the future easier. (Rather than needing to go out and find the dist url, you just have to modify the package.json). It would make it a bit easier, you just have to import the css from the package.

2023-03-14 22:53 UTC, VividLemon commented on apps/nuxt-playground/.gitignore
> +node_modules
This is a general note about the entire nuxt-playground...

It may be better instead to start working on an entire docs rewrite that is using Nuxt. My plan is to use Nuxt & Nuxt Content to write the docs.

That way the playground can stay how it is (relatively unused), and the docs rewritten in Nuxt can serve as a useful testing ground for nuxt support.

2023-03-14 22:53 UTC, xvaara commented on apps/nuxt-playground/components
> +../playground/src/components
it is a symlink

2023-03-14 22:54 UTC, VividLemon commented on apps/nuxt-playground/.npmrc
> +shamefully-hoist=true
I'm surprised anything is working at all. It should be behaving as if shamefully-hoist is false

2023-03-14 22:56 UTC, VividLemon commented on apps/nuxt-playground/.gitignore
> +node_modules
The docs rewrite is a useful feature since VuePress is fairly unmaintained compared to VitePress & Nuxt. I hesitate to say they are "deprecated", but VitePress is the official recommendation over VuePress, but either way it would be better for the docs to bring forth Nuxt specific issues, since most of the user base that wants SSR will likely be using Nuxt

2023-03-14 22:59 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +useEventListener(element, 'toggle', () => {
I apologize that I didn't bring this up in the earlier critique about vBModal addition, but it may be useful to prepend the event with a specific Bootstrap vue event listener, as to not be conflicting with users. Perhaps `bv-toggle` would be more appropriate. I am not sure how Bootstrap vue does this. If they do what you did here, it can stay fine, but if they have a specific way they have been doing it, it may be best to follow their convention

2023-03-14 23:01 UTC, VividLemon requested changes

2023-03-14 23:01 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BToast/plugin.ts
> +const injectkey = Symbol('toast')
I am aware that this isn't your doing. I'm not sure if you did anything to Toasts in this PR, but Toast needs to get an overhaul as well. afaik it's been broken for awhile.

2023-03-14 23:01 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BModal.ts
> +export default BToggle
lol

2023-03-14 23:06 UTC, VividLemon commented on apps/nuxt-playground/components
> +../playground/src/components
In that case it may be better to review https://github.com/bootstrap-vue/bootstrap-vue-next/pull/969#discussion_r1136320173

2023-03-14 23:11 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BToast/plugin.ts
> +const injectkey = Symbol('toast')
They aren't used outside this file. And I don't think that is in the scope of this pull request. I forgot I added names to Symbols when trying to figure out why they didn't work. I can reset the file to the original.

2023-03-14 23:13 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BModal.ts
> +export default BToggle
Well... 😆 I could have also exported BToggle two times on different names, but that seemed like a possibility for confusion.

2023-03-15 00:16 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +useEventListener(element, 'toggle', () => {
bootstrap-vue uses vue2 $on and $emit on the root node to create a eventBus. It's a hacky way and it's not supported in vue3 without compat build. I just figured since we look for css-selector or ref, we could just sen an html event to it to make it simple. Toggle official event for anything... and I think now you could add <div id="foo" @toggle="doSomething"> and trigger that with the directive.

2023-03-15 00:17 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +useEventListener(element, 'toggle', () => {
Well I did put a foot in my mouth: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event

but that's the only element that has that event :D

2023-03-15 00:26 UTC, xvaara commented on apps/nuxt-playground/.gitignore
> +node_modules
Should we add some ssr for the App.vue in the main package then, so that ssr errors are caught early?
It's not that hard, little express server with vite middleware.
Or is the ssr test going to be building the doc to html?

2023-03-15 00:27 UTC, xvaara commented on apps/nuxt-playground/.gitignore
> +node_modules
maybe add https://test-utils.vuejs.org/guide/advanced/ssr.html to all the components?

2023-03-15 00:31 UTC, VividLemon commented on apps/nuxt-playground/.gitignore
> +node_modules
> maybe add https://test-utils.vuejs.org/guide/advanced/ssr.html to all the components?

Such a test would be too brittle. Any slight change would break this test.

> Or is the ssr test going to be building the doc to html?

This should be sufficient.

2023-03-23 02:47 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BToggle.ts
> +    el.addEventListener('click', () => toggle(binding, el))
Not sure if event listeners are automatically destroyed. You may want to clean this up manually, but maybe I'm wrong and nothing needs to happen

2023-03-23 11:49 UTC, xvaara commented on packages/bootstrap-vue-next/src/directives/BToggle.ts
> +    el.addEventListener('click', () => toggle(binding, el))
Yes, forgot to do that. Good catch.

2023-03-24 02:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const open = useVModel(props, 'modelValue', emit, {passive: true})
```suggestion
const open = useVModel(props, 'modelValue', emit, {passive: true})
const openBoolean = useBooleanish(open)
```

2023-03-24 02:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const open = useVModel(props, 'modelValue', emit, {passive: true})
Expand this to work, of course

2023-03-24 02:37 UTC, VividLemon requested changes

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +const element = ref<HTMLElement>(null as unknown as HTMLElement)
```suggestion
const element = ref<HTMLElement | null>(null)
```

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +  if (newValue === oldValue) return
Under what circumstance would this occur

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +  if (newValue === oldValue) return
You should probably watch modelValueBoolean instead for more accurate values

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +function getTransitionDelay(element: HTMLElement) {
use arrow function

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BToggle.ts
> + */
```suggestion
```

2023-03-24 02:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/directives/BToggle.ts
> + */
Removing this globally. It's kind of dumb

2023-03-24 02:38 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCollapse.vue
> +const element = ref<HTMLElement>(null as unknown as HTMLElement)
& fix whatever issues "nullability" causes

2023-03-24 02:39 UTC, VividLemon commented
After above changes, one more full PR review from me, then if I don't find anything else, it is done

2023-03-26 14:28 UTC, merged